--
-- PostgreSQL database dump
--

-- Dumped from database version 11.1
-- Dumped by pg_dump version 11.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: gender_types; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.gender_types AS ENUM (
    'not_specified',
    'male',
    'female',
    'non_bianary'
);


--
-- Name: role; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.role AS ENUM (
    'player',
    'guardian',
    'staff'
);


--
-- Name: team_gender; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.team_gender AS ENUM (
    'male',
    'female',
    'coed'
);


--
-- Name: team_level; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.team_level AS ENUM (
    'not_set',
    'recreational',
    'competitive',
    'school'
);


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addresses (
    id integer NOT NULL,
    street text,
    street2 text,
    city text,
    state text,
    zip_code text,
    latitude numeric,
    longitude numeric,
    verification_info text,
    original_attributes text,
    user_id integer NOT NULL
);


--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: age_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.age_groups (
    id integer NOT NULL,
    title text,
    max_age integer,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: age_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.age_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.age_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clubs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clubs (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: clubs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clubs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clubs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: divisions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.divisions (
    id integer NOT NULL,
    name text,
    description text,
    parent_id integer
);


--
-- Name: divisions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.divisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.divisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: households; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.households (
    id integer NOT NULL,
    name text,
    user_id integer
);


--
-- Name: households_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.households ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.households_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: season_teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_teams (
    id integer NOT NULL,
    team_id integer,
    season_id integer,
    division_id integer,
    is_active boolean DEFAULT true NOT NULL
);


--
-- Name: season_teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.season_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.season_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seasons (
    id integer NOT NULL,
    name text,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    active boolean DEFAULT true NOT NULL
);


--
-- Name: seasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_rosters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_rosters (
    id integer NOT NULL,
    user_id integer,
    team_id integer,
    season_id integer,
    roles text[],
    is_active boolean DEFAULT true NOT NULL,
    "position" text
);


--
-- Name: team_rosters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_rosters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_rosters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    name text,
    zip_code text,
    time_zone text,
    gender public.team_gender,
    level public.team_level,
    club_id integer NOT NULL,
    age_group_id integer
);


--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email text NOT NULL,
    password_digest text,
    first_name text NOT NULL,
    middle_name text,
    last_name text NOT NULL,
    nickname text,
    club_role public.role DEFAULT 'player'::public.role NOT NULL,
    gender public.gender_types DEFAULT 'not_specified'::public.gender_types NOT NULL,
    mobile_number text,
    mobile_number_country_code text,
    authy_id text,
    date_of_birth timestamp without time zone,
    mobile_number_verified boolean DEFAULT false NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    account_is_active boolean DEFAULT true NOT NULL,
    invited_to_dashboard boolean DEFAULT false NOT NULL,
    invite_accepted boolean DEFAULT false NOT NULL,
    is_club_owner boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    club_id integer NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: age_groups age_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.age_groups
    ADD CONSTRAINT age_groups_pkey PRIMARY KEY (id);


--
-- Name: clubs clubs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_pkey PRIMARY KEY (id);


--
-- Name: divisions divisions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.divisions
    ADD CONSTRAINT divisions_pkey PRIMARY KEY (id);


--
-- Name: households households_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.households
    ADD CONSTRAINT households_pkey PRIMARY KEY (id);


--
-- Name: households households_user_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.households
    ADD CONSTRAINT households_user_id_name_key UNIQUE (user_id, name);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: season_teams season_teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_teams
    ADD CONSTRAINT season_teams_pkey PRIMARY KEY (id);


--
-- Name: seasons seasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT seasons_pkey PRIMARY KEY (id);


--
-- Name: team_rosters team_rosters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_rosters
    ADD CONSTRAINT team_rosters_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: addresses_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX addresses_user_id_index ON public.addresses USING btree (user_id);


--
-- Name: divisions_parent_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX divisions_parent_id_index ON public.divisions USING btree (parent_id);


--
-- Name: season_teams_division_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX season_teams_division_id_index ON public.season_teams USING btree (division_id);


--
-- Name: season_teams_season_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX season_teams_season_id_index ON public.season_teams USING btree (season_id);


--
-- Name: season_teams_team_id_division_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX season_teams_team_id_division_id_index ON public.season_teams USING btree (team_id, division_id);


--
-- Name: season_teams_team_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX season_teams_team_id_index ON public.season_teams USING btree (team_id);


--
-- Name: season_teams_team_id_season_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX season_teams_team_id_season_id_index ON public.season_teams USING btree (team_id, season_id);


--
-- Name: team_rosters_user_id_team_id_season_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX team_rosters_user_id_team_id_season_id_index ON public.team_rosters USING btree (user_id, team_id, season_id);


--
-- Name: users_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_email_index ON public.users USING btree (email);


--
-- Name: addresses addresses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: households households_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.households
    ADD CONSTRAINT households_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: season_teams season_teams_division_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_teams
    ADD CONSTRAINT season_teams_division_id_fkey FOREIGN KEY (division_id) REFERENCES public.divisions(id);


--
-- Name: season_teams season_teams_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_teams
    ADD CONSTRAINT season_teams_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: season_teams season_teams_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_teams
    ADD CONSTRAINT season_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: team_rosters team_rosters_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_rosters
    ADD CONSTRAINT team_rosters_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: team_rosters team_rosters_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_rosters
    ADD CONSTRAINT team_rosters_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id);


--
-- Name: team_rosters team_rosters_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_rosters
    ADD CONSTRAINT team_rosters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

SET search_path TO ["mine", "public"];
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224000000_create_enums.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224002601_create_users.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224061729_create_teams.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224063918_create_divisions.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224064025_create_households.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224064627_create_age_groups.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224064759_create_addresses.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224064937_create_seasons.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224065936_create_team_rosters.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224071624_create_clubs.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181224210735_add_foreign_keys_to_tables.rb');
INSERT INTO "schema_migrations" ("filename") VALUES ('20181225180251_add_season_teams.rb');